# Generated by Django 3.0.8 on 2020-07-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_id',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='Slack ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='team_id',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='Team ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='Team ID'),
        ),
    ]
