# Generated by Django 3.0.8 on 2020-09-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20200722_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='Title'),
        ),
    ]
